name: Container Scanning
on: [push, pull_request]
jobs:
 trivy-scan:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout Code
 uses: actions/checkout@v2
- name: Run Trivy vulnerability scanner
 uses: aquasecurity/trivy-action@master
 with:
 image-ref: 'your-docker-image-name'