name: DAST
on: [deployment]
jobs:
 zap-scan:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v2
- name: ZAP Scan
 uses: zaproxy/action-baseline@v0.4.0
 with:
 target: 'https://your-deployment-url.com'