name: Secret Scanning
on: [push, pull_request]
jobs:
 git-secrets:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout Code
 uses: actions/checkout@v2
- name: Run git-secrets
 uses: aws-actions/git-secrets-scan@master