####https://resources.github.com/learn/pathways/automation/intermediate/create-reusable-workflows-in-github-actions/
##on:  # Specifies the event triggering the workflow
##  workflow_call:  # Indicates that this is a reusable workflow
##    inputs:  # Defines the inputs that can be passed from the caller workflow
##      config-path:  # Name of the input
##        required: true  # Specifies that this input is mandatory
##        type: string  # Specifies the type of the input
##    secrets:  # Defines the secrets that can be passed from the caller workflow
##      envPAT:  # Name of the secret
##        required: true  # Specifies that this secret is mandatory

name: reusable-workflow
on:
  workflow_call:
    inputs:
      node-version:
        description: "Versión de Node"
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: echo ${{ inputs.node-version }}

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
            target: 'https://www.zaproxy.org'